# Site settings
title: Letters From N
email: atticus@lettersfromn.com
baseurl: "/"
url: "http://lettersfromn.com" # the base hostname & protocol for your site
markdown: redcarpet
highlighter: pygments
gems:
  - jekyll-sitemap
